# Generated by Django 4.2.6 on 2023-10-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='producter',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='producter',
            name='name',
            field=models.CharField(max_length=65, verbose_name='Имя'),
        ),
    ]
