# Generated by Django 4.2.6 on 2023-10-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='producter',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.IntegerField(default='-', verbose_name='Год оконания выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='start_year',
            field=models.IntegerField(verbose_name='Год начала выпуска'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(max_length=254, verbose_name='Email автора'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='producter',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.country'),
        ),
    ]
