# Generated by Django 4.2.6 on 2023-10-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_alter_car_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
