# Generated by Django 4.2.6 on 2023-10-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='producter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.producter', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='producter',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.country', verbose_name='Страна'),
        ),
    ]
