# Generated by Django 4.2.6 on 2023-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0007_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
