# Generated by Django 4.2.6 on 2023-10-20 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0009_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.IntegerField(verbose_name='Год оконания выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='producter',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producters', to='talk.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='producter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
