# Generated by Django 4.2.6 on 2023-10-20 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0010_alter_car_last_year_alter_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='producter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='talk.producter', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='talk.car', verbose_name='Автомобиль'),
        ),
    ]
