# Generated by Django 4.2.6 on 2023-10-21 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0012_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
