# Generated by Django 4.2.6 on 2023-10-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0013_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Комментарий'),
        ),
    ]
