# Generated by Django 4.2.6 on 2023-10-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0014_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producter',
            table='producter',
        ),
    ]
