# Generated by Django 4.2.6 on 2023-10-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0015_alter_producter_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producter',
            table=None,
        ),
    ]
